/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  programmingSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  //  programmingSidebar: [
  //   'intro',
  //   'programming/congratulations',
  //   'programming/create-a-blog-post',
  //   'programming/create-a-document',
  //   {
  //     type: 'category',
  //     label: 'programming',
  //     items: ['programming/create-a-document', 'programming/create-a-blog-post', 'programming/create-a-document'],
  //   },
  // ],
  
};

export default sidebars;
